# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 03:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MIT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=420)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.CharField(blank=True, default='', max_length=420)),
                ('starting_balance', models.FloatField(default=0.0)),
                ('interest_rate', models.IntegerField(default=0)),
                ('short', models.BooleanField()),
                ('counter', models.IntegerField(blank=True, default=0)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='net_worth',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='remaining_balance',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MIT.Game'),
        ),
    ]
