# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIT', '0002_auto_20171104_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='interest_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=420),
        ),
        migrations.AlterField(
            model_name='game',
            name='starting_balance',
            field=models.FloatField(),
        ),
    ]
