# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MIT', '0005_auto_20171104_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='MIT.Game'),
        ),
    ]
