# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 04:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MIT', '0008_auto_20171118_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=50)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('order_time', models.DateTimeField(blank=True)),
                ('transaction_type', models.CharField(max_length=20)),
                ('shares', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MIT.Game')),
            ],
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MIT.Game'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MIT.Player'),
        ),
    ]
