# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MIT', '0012_auto_20171119_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=50)),
                ('stock_type', models.CharField(default='INVALID', max_length=20)),
                ('shares', models.IntegerField(default=0)),
                ('total_value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='total_value',
            new_name='current_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='game',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='player',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='shares',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_type',
        ),
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MIT.Player'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='INVALID', max_length=20),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MIT.Game'),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MIT.Player'),
        ),
    ]
