# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIT', '0016_auto_20171128_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='yesterday_net_worth',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
